# Generated by Django 4.2.4 on 2023-08-19 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
